#!/usr/bin/env python3
"""Local fake data for index.html. Nothing here touches Google.

  python3 dev/seed.py seed [density]   build dev/index.html with random OFF cells (default 0.3)
  python3 dev/seed.py unseed           rebuild it with every cell blank

The built page swaps window.fetch for an in-page stub, so the real UI runs
unchanged against in-memory data. Open http://localhost:8731/#local-1 to act
as the first person, #local-2 the second, and so on. No hash is view-only.
"""
import json, random, sys
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "index.html"
OUT = ROOT / "dev" / "index.html"

NAMES = ["Ada Lovelace", "Brian Kernighan", "Carol Shaw", "Dennis Ritchie", "Erin Catto",
         "Frances Allen", "Grace Hopper", "Hedy Lamarr", "Ivan Sutherland", "Joan Clarke",
         "Ken Thompson", "Linus Torvalds", "Margaret Hamilton", "Niklaus Wirth", "Olga Ladyzhenskaya",
         "Peter Norvig", "Radia Perlman", "Sophie Wilson", "Tim Berners-Lee", "Ursula Franklin",
         "Vint Cerf", "Wendy Hall"]
START, DAYS = date(2026, 12, 21), 19

def grid(density):
    dates = [{"label": (START + timedelta(d)).strftime("%a %-d %b"),
              "weekend": (START + timedelta(d)).weekday() >= 5} for d in range(DAYS)]
    off = [[random.random() < density for _ in dates] for _ in NAMES]
    return {"dates": dates, "names": NAMES, "off": off}

def build(data):
    html = SRC.read_text()
    stub = f"""<script>
// LOCAL DEV STUB. Generated by dev/seed.py. Not the real API.
window.__DATA = {json.dumps(data)};
window.__TOKENS = Object.fromEntries(window.__DATA.names.map(function (n, i) {{ return ['local-' + (i + 1), n]; }}));
window.fetch = function (url, opts) {{
  return new Promise(function (resolve) {{
    setTimeout(function () {{
      var d = window.__DATA;
      if (opts && opts.method === 'POST') {{
        var b = JSON.parse(opts.body);
        var name = window.__TOKENS[b.token];
        if (!name) return resolve({{ json: function () {{ return Promise.resolve({{ ok: false, error: 'Unknown link. Use the one you were sent.' }}); }} }});
        var r = d.names.indexOf(name), c = d.dates.findIndex(function (x) {{ return x.label === b.date; }});
        d.off[r][c] = !!b.off;
        return resolve({{ json: function () {{ return Promise.resolve({{ ok: true }}); }} }});
      }}
      var tok = new URL(url, location.href).searchParams.get('token');
      var g = JSON.parse(JSON.stringify(d));
      g.me = window.__TOKENS[tok] || null;
      resolve({{ json: function () {{ return Promise.resolve(g); }} }});
    }}, 250);
  }});
}};
</script>
"""
    OUT.write_text(html.replace("<script>", stub + "<script>", 1))

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "seed"
    if cmd == "seed":
        density = float(sys.argv[2]) if len(sys.argv) > 2 else 0.3
        data = grid(density)
        build(data)
        n = sum(map(sum, data["off"]))
        print(f"seeded {n} of {len(NAMES) * DAYS} cells OFF -> {OUT.relative_to(ROOT)}")
    elif cmd == "unseed":
        build(grid(0))
        print(f"cleared -> {OUT.relative_to(ROOT)}")
    else:
        sys.exit(__doc__)
